import type { Metadata } from 'next';
import { Inter, Figtree } from 'next/font/google';
import 'antd/dist/antd.css';
import './globals.css';
import { Providers } from '@/redux/provider';
import Provider from '@/components/Provider';
import Header from '@/components/Header/Header';
import SEO from '@/components/SEO/SEO';
import Footer from '@/components/Footer/Footer';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

const figtree = Figtree({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <Script
          async
          strategy='lazyOnload'
          type='text/javascript'
          src='https://sm1.selectmedia.asia/cdn/tags/tag_b2c437e2-496c-4159-ab0a-61c48f90e12b.js'
        ></Script>
        <SEO />
      </head>
      <body className={`${inter.className} ${figtree.className}`}>
        <Providers>
          <Provider>
            <Header />
            {children}
            <Footer />
          </Provider>
        </Providers>
      </body>
    </html>
  );
}
