import type { Metadata } from 'next';
import { Inter, Figtree } from 'next/font/google';
import 'antd/dist/antd.css';
import './globals.css';
import { Providers } from '@/redux/provider';
import Provider from '@/components/Provider';
import Header from '@/components/Header/Header';
import SEO from '@/components/SEO/SEO';

const inter = Inter({ subsets: ['latin'] });

const figtree = Figtree({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <SEO />
      </head>
      <body className={`${inter.className} ${figtree.className}`}>
        <Providers>
          <Provider>
            <Header />
            {children}
          </Provider>
        </Providers>
      </body>
    </html>
  );
}
